### ISSUE TITLE
Incompatible with EnderCore?

### ISSUE THREAD

**Issue by unilock** [TwilightFlower/lwjgl3ify#3]
The game crashes during startup with [EnderCore](https://www.curseforge.com/minecraft/mc-mods/endercore) installed alongside lwjgl3ify.

```
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:38)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[15:44:45] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:698]: 	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: Caused by: java.lang.ClassNotFoundException: Exception caught while transforming class net.minecraft.entity.player.EntityPlayer
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:294)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:660]: 	... 9 more
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer com.enderio.core.common.transform.EnderCoreTransformer@5c7876e1 from coremod EnderCorePlugin
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: 	at RFB-Launch//net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: 	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:405)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: 	at RFB-System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:292)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:673]: 	... 11 more
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:lockedPrintStackTrace:696]: Caused by: java.lang.IllegalArgumentException: Class versions V1_5 or less must use F_NEW frames.
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:781)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at RFB-Launch//com.enderio.core.common.transform.EnderCoreTransformer.transform(EnderCoreTransformer.java:296)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	at RFB-Launch//net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
[15:44:45] [main/INFO] [STDERR]: [java.lang.Throwable:lockedPrintStackTrace:696]: 	... 13 more
```

**Comment by iristhepianist** [comment]
I have had this issue too.
Any solutions?

**Comment by Irgendwer01** [comment]
Fixed with 01b4c06

**Comment by unilock** [comment]
Lovely ^^
