### ISSUE TITLE
Incompatible with Botania Tweaks

### ISSUE THREAD

**Issue by unilock** [TwilightFlower/lwjgl3ify#4]
The game crashes during startup with [Botania Tweaks](https://www.curseforge.com/minecraft/mc-mods/botania-tweaks) installed alongside lwjgl3ify.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania Tweaks (botania_tweaks)
Caused by: java.lang.NoClassDefFoundError: sun/reflect/Reflection
    at quaternary.botaniatweaks.modules.shared.lib.NiceTryMap.<clinit>(NiceTryMap.java:22)
    at quaternary.botaniatweaks.modules.botania.config.BotaniaConfig.<clinit>(BotaniaConfig.java:24)
    at quaternary.botaniatweaks.modules.botania.ModuleBotania.readConfig(ModuleBotania.java:75)
    at quaternary.botaniatweaks.modules.shared.config.BotaniaTweaksConfig.readConfig(BotaniaTweaksConfig.java:31)
    at quaternary.botaniatweaks.modules.shared.config.BotaniaTweaksConfig.initConfig(BotaniaTweaksConfig.java:24)
    at quaternary.botaniatweaks.BotaniaTweaks.preinit(BotaniaTweaks.java:57)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
Caused by: java.lang.ClassNotFoundException: sun.reflect.Reflection
    at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader.findClass(RfbSystemClassLoader.java:187)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:218)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    ... 43 more
```

**Comment by Irgendwer01** [comment]
Fixed as of #15
