### ISSUE TITLE
Several mods crash when their Forge event listeners are invoked - "IncompatibleClassChangeError: Method '...' must be InterfaceMethodref constant"

### ISSUE THREAD

**Issue by unilock** [TwilightFlower/lwjgl3ify#5]
As the title says, I've had several mods crash the game when joining a world, apparently when their Forge event listeners are being invoked. The common error is `IncompatibleClassChangeError: Method '...' must be InterfaceMethodref constant`.

<details>

<summary><a href="https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry">Electroblob's Wizardry</a></summary>

```
java.lang.IncompatibleClassChangeError: Method 'void electroblob.wizardry.enchantment.Imbuement.onEntityJoinWorld(net.minecraftforge.event.entity.EntityJoinWorldEvent)' must be InterfaceMethodref constant
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_874_Imbuement_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.world.World.spawnEntity(World.java:1209)
    at net.minecraft.world.WorldServer.spawnEntity(WorldServer.java:1058)
    at net.minecraft.server.management.PlayerList.playerLoggedIn(PlayerList.java:377)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:166)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817)
    at java.lang.Thread.run(Thread.java:1583)
```

</details>

<details>

<summary><a href="https://www.curseforge.com/minecraft/mc-mods/librarianlib">LibrarianLib</a></summary>

```
java.lang.IncompatibleClassChangeError: Method 'void com.teamwizardry.librarianlib.features.base.block.IMultipleComponentGeometry.onDrawBlockHighlight(net.minecraftforge.client.event.DrawBlockHighlightEvent)' must be InterfaceMethodref constant
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_345_IMultipleComponentGeometry_onDrawBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:191)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1361)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
```

</details>

<details>

<summary><a href="https://www.curseforge.com/minecraft/mc-mods/plusticminusbad">xXx_MoreToolMats_xXx</a></summary>

```
java.lang.IncompatibleClassChangeError: Method 'void landmaster.plustic.tools.IToggleTool.onInput(net.minecraftforge.fml.common.gameevent.InputEvent$KeyInputEvent)' must be InterfaceMethodref constant
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1967_IToggleTool_onInput_KeyInputEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2017)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5614)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
```

</details>

**Comment by Irgendwer01** [comment]
Fixed as of b0f776c
